[[datasets]]
video_directory = "Genshin_Impact_Scaramouche_Storyline_Video_Captioned_Tiny_960x544x6"
target_frames = [1, 25, 45]
frame_extraction = "head"
resolution = [960, 544]
caption_extension = ".txt"
batch_size = 1
enable_bucket = true
bucket_no_upscale = false

[[datasets]]
image_directory = "Genshin_Impact_Scaramouche_Images_Captioned_Local"
resolution = [ 1024, 1024,]
caption_extension = ".txt"
batch_size = 1
enable_bucket = true
bucket_no_upscale = false